/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.AgregarUsuario;
import GUI.EliminarUsuario;
import GUI.ModficarUsuario;
import GUI.ConsultarUsuario;
import GUI.POS;

import javax.swing.ImageIcon;


public class Admin extends javax.swing.JFrame {

    public int ventanaA = 1;
    public Admin() {
        initComponents();
        ImageIcon icon = new ImageIcon("C:\\Users\\afrp0\\OneDrive\\Documentos\\PruebasProyecto-20250408T204547Z-001\\PruebasProyecto\\src\\img\\Logo.png"); // Cambia 
        setIconImage(icon.getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AgregarU = new javax.swing.JMenuItem();
        EliminarU = new javax.swing.JMenuItem();
        ModificarU = new javax.swing.JMenuItem();
        ConsultarU = new javax.swing.JMenuItem();
        menuInventario = new javax.swing.JMenu();
        agregarProducto = new javax.swing.JMenuItem();
        modificarProducto = new javax.swing.JMenuItem();
        eliminarProducto = new javax.swing.JMenuItem();
        mostrarInventario = new javax.swing.JMenuItem();
        POS = new javax.swing.JMenu();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(226, 223, 208));

        jDesktopPane1.setBackground(new java.awt.Color(226, 223, 208));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(850, 570));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gerente.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(233, 233, 233))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel1)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("Usuarios");

        AgregarU.setText("Agregar");
        AgregarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUActionPerformed(evt);
            }
        });
        jMenu1.add(AgregarU);

        EliminarU.setText("Eliminar");
        EliminarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUActionPerformed(evt);
            }
        });
        jMenu1.add(EliminarU);

        ModificarU.setText("Modificar");
        ModificarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUActionPerformed(evt);
            }
        });
        jMenu1.add(ModificarU);

        ConsultarU.setText("Consultar");
        ConsultarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarUActionPerformed(evt);
            }
        });
        jMenu1.add(ConsultarU);

        jMenuBar1.add(jMenu1);

        menuInventario.setText("Inventario");

        agregarProducto.setText("Agregar Producto");
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });
        menuInventario.add(agregarProducto);

        modificarProducto.setText("Modificar Producto");
        modificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductoActionPerformed(evt);
            }
        });
        menuInventario.add(modificarProducto);

        eliminarProducto.setText("Eliminar Producto");
        eliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProductoActionPerformed(evt);
            }
        });
        menuInventario.add(eliminarProducto);

        mostrarInventario.setText("Mostrar Inventario");
        mostrarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarInventarioActionPerformed(evt);
            }
        });
        menuInventario.add(mostrarInventario);

        jMenuBar1.add(menuInventario);

        POS.setText("POS");
        POS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                POSMouseClicked(evt);
            }
        });
        jMenuBar1.add(POS);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUActionPerformed
        AgregarUsuario ventanaAgregar = new AgregarUsuario();
        jDesktopPane1.add(ventanaAgregar);
        ventanaAgregar.setVisible(true);
        ventanaAgregar.setResizable(false);
        ventanaAgregar.setLocation(205, 140);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ventanaAgregar.getUI()).setNorthPane(null);
        ventanaAgregar.setBorder(null);
    }//GEN-LAST:event_AgregarUActionPerformed

    private void EliminarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUActionPerformed
        EliminarUsuario ventanaEliminar = new EliminarUsuario();
        jDesktopPane1.add(ventanaEliminar);
        ventanaEliminar.setVisible(true);
        ventanaEliminar.setResizable(false);
        ventanaEliminar.setLocation(140, 140);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ventanaEliminar.getUI()).setNorthPane(null);
        ventanaEliminar.setBorder(null);
    }//GEN-LAST:event_EliminarUActionPerformed

    private void ModificarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUActionPerformed
        ModficarUsuario ventanaModificar = new ModficarUsuario();
        jDesktopPane1.add(ventanaModificar);
        ventanaModificar.setVisible(true);
        ventanaModificar.setResizable(false);
        ventanaModificar.setLocation(218, 140);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ventanaModificar.getUI()).setNorthPane(null);
        ventanaModificar.setBorder(null);
    }//GEN-LAST:event_ModificarUActionPerformed

    private void ConsultarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarUActionPerformed
        ConsultarUsuario ventanaConsultar = new ConsultarUsuario();
        jDesktopPane1.add(ventanaConsultar);
        ventanaConsultar.setVisible(true);
        ventanaConsultar.setResizable(false);
        ventanaConsultar.setLocation(215, 140);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ventanaConsultar.getUI()).setNorthPane(null);
        ventanaConsultar.setBorder(null);
    }//GEN-LAST:event_ConsultarUActionPerformed

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
        AgregarProducto ventanaAgregarProducto = new AgregarProducto();
        jDesktopPane1.add(ventanaAgregarProducto);
        ventanaAgregarProducto.setVisible(true);
        ventanaAgregarProducto.setResizable(false);
        ventanaAgregarProducto.setLocation(200, 140);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ventanaAgregarProducto.getUI()).setNorthPane(null);
        ventanaAgregarProducto.setBorder(null);
    }//GEN-LAST:event_agregarProductoActionPerformed

    private void modificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductoActionPerformed
        ModificarProducto ventanaModificarProducto = new ModificarProducto();
        jDesktopPane1.add(ventanaModificarProducto);
        ventanaModificarProducto.setVisible(true);
        ventanaModificarProducto.setResizable(false);
        ventanaModificarProducto.setLocation(200, 110);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ventanaModificarProducto.getUI()).setNorthPane(null);
        ventanaModificarProducto.setBorder(null);
    }//GEN-LAST:event_modificarProductoActionPerformed

    private void eliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProductoActionPerformed
        EliminarProducto ventanaEliminarProducto = new EliminarProducto();
        jDesktopPane1.add(ventanaEliminarProducto);
        ventanaEliminarProducto.setVisible(true);
        ventanaEliminarProducto.setResizable(false);
        ventanaEliminarProducto.setLocation(220, 100);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ventanaEliminarProducto.getUI()).setNorthPane(null);
        ventanaEliminarProducto.setBorder(null);
    }//GEN-LAST:event_eliminarProductoActionPerformed

    private void mostrarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarInventarioActionPerformed
        MostrarInventario ventanaMostrarInventario = new MostrarInventario();
        
        jDesktopPane1.add(ventanaMostrarInventario);
        ventanaMostrarInventario.setVisible(true);
        ventanaMostrarInventario.setResizable(false);
        ventanaMostrarInventario.setLocation(0, 140);
        
    }//GEN-LAST:event_mostrarInventarioActionPerformed

    private void POSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_POSMouseClicked
        
        POS ventanaPOS = new POS();
        
        jDesktopPane1.add(ventanaPOS);
        ventanaPOS.setVisible(true);
        ventanaPOS.setResizable(false);
        ventanaPOS.setLocation(100, 0);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ventanaPOS.getUI()).setNorthPane(null);
        ventanaPOS.setBorder(null);
    }//GEN-LAST:event_POSMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarU;
    private javax.swing.JMenuItem ConsultarU;
    private javax.swing.JMenuItem EliminarU;
    private javax.swing.JMenuItem ModificarU;
    private javax.swing.JMenu POS;
    private javax.swing.JMenuItem agregarProducto;
    private javax.swing.JMenuItem eliminarProducto;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuInventario;
    private javax.swing.JMenuItem modificarProducto;
    private javax.swing.JMenuItem mostrarInventario;
    // End of variables declaration//GEN-END:variables
}
