/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author afrp0
 */
public class AgregarProducto extends javax.swing.JInternalFrame {

    
    private BaseDeDatos.Producto agregarProducto;
    public AgregarProducto() {
        initComponents();
        agregarProducto = new BaseDeDatos.Producto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        txtPrecioUnitario = new javax.swing.JTextField();
        txtProveedor = new javax.swing.JTextField();
        txtFechaIngreso = new javax.swing.JTextField();
        txtFechaVencimiento = new javax.swing.JTextField();
        txtUnidadMedida = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        txtRentabilidad = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPorcentajeIva = new javax.swing.JTextField();
        txtPrecioFinal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(226, 223, 208));
        setBorder(null);
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(450, 550));

        jLabel1.setText("Codigo producto");

        jLabel2.setText("Nombre producto");

        jLabel3.setText("Unidad de medida");

        jLabel4.setText("Precio unitario");

        jLabel5.setText("Rentabilidad");

        jLabel7.setText("Cantidad");

        jLabel8.setText("Fecha ingreso");

        jLabel9.setText("Fecha vencimiento");

        txtCodigoProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtUnidadMedida.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtNombreProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        agregar.setBackground(new java.awt.Color(233, 115, 0));
        agregar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        agregar.setForeground(new java.awt.Color(226, 223, 208));
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        txtPrecioVenta.setEditable(false);

        jLabel10.setText("Porcentaje IVA");

        txtPrecioFinal.setEditable(false);

        jLabel12.setText("Proveedor");

        jButton2.setText("Calcular Precio Venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Calcular Precio Final");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(226, 223, 208));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("X");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtNombreProducto)
                            .addComponent(txtUnidadMedida)
                            .addComponent(txtPrecioUnitario)
                            .addComponent(txtProveedor)
                            .addComponent(txtFechaIngreso)
                            .addComponent(txtFechaVencimiento)
                            .addComponent(txtRentabilidad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrecioVenta)
                            .addComponent(txtPorcentajeIva)
                            .addComponent(txtPrecioFinal)
                            .addComponent(txtCantidad))))
                .addGap(24, 24, 24)
                .addComponent(jButton4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)))
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRentabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPorcentajeIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        double codigoProducto = Double.parseDouble(txtCodigoProducto.getText());
        String nombreProducto = txtNombreProducto.getText();
        String unidadMedida = txtUnidadMedida.getText();
        double precioUnitario = Double.parseDouble(txtPrecioUnitario.getText());
        double rentabilidad = Double.parseDouble(txtRentabilidad.getText());
        double precioVenta = Double.parseDouble(txtPrecioVenta.getText());
        double porcentajeIva = Double.parseDouble(txtPorcentajeIva.getText());
        double precioFinal = Double.parseDouble(txtPrecioFinal.getText());
        int cantidad = Integer.parseInt(txtCantidad.getText());
        String proveedor = txtProveedor.getText();
        String fechaIngreso = txtFechaIngreso.getText();
        String fechaVencimiento = txtFechaVencimiento.getText();
        
        
        if(evt.getSource() == agregar){
        agregarProducto = new BaseDeDatos.Producto();
        
        try{
            if (agregarProducto.ProductoExistente(codigoProducto) && agregarProducto.ProductoExistente(codigoProducto)) {
            JOptionPane.showMessageDialog(this, "El codigo del producto ya existe. Por favor, ingrese un codigo diferente.");
        } else {
            // Llamar al método AgregarProducto con los valores convertidos
            if (agregarProducto.AgregarProducto(codigoProducto, nombreProducto, precioUnitario, cantidad, porcentajeIva, unidadMedida, proveedor, fechaIngreso, fechaVencimiento,precioVenta ,rentabilidad , precioFinal)) {
                // Producto agregado exitosamente
                JOptionPane.showMessageDialog(this, "Producto agregado exitosamente.");
                
                // Limpiar los campos de texto
                txtCodigoProducto.setText("");
                txtNombreProducto.setText("");
                txtUnidadMedida.setText("");
                txtPrecioUnitario.setText("");
                txtRentabilidad.setText("");
                txtPrecioVenta.setText("");
                txtPorcentajeIva.setText("");
                txtPrecioFinal.setText("");
                txtCantidad.setText("");
                txtProveedor.setText("");
                txtFechaIngreso.setText("");
                txtFechaVencimiento.setText("");
            } else {
                // Error al agregar el usuario
                JOptionPane.showMessageDialog(this, "Error al agregar el producto.");
            }
            }
        
        }   catch (NumberFormatException e) {
        // Manejo de la excepción si la conversión falla
        JOptionPane.showMessageDialog(this, "Por favor ingrese los datos correctamente");
    }
        
        
        
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double precioUnitario = Double.parseDouble(txtPrecioUnitario.getText());
        double rentabilidad = Double.parseDouble(txtRentabilidad.getText());
        double resultado = (precioUnitario * rentabilidad)+precioUnitario;
        txtPrecioVenta.setText(String.valueOf(resultado));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if(!"".equals(txtPrecioVenta.getText())){
            double precioVenta = Double.parseDouble(txtPrecioVenta.getText());
            double iva = Double.parseDouble(txtPorcentajeIva.getText());
            double resultado = (precioVenta * iva)+precioVenta;
            txtPrecioFinal.setText(String.valueOf(resultado));
        }else{
            JOptionPane.showMessageDialog(this, "Primero debe calcular el precio de venta");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtFechaIngreso;
    private javax.swing.JTextField txtFechaVencimiento;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPorcentajeIva;
    private javax.swing.JTextField txtPrecioFinal;
    private javax.swing.JTextField txtPrecioUnitario;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtRentabilidad;
    private javax.swing.JTextField txtUnidadMedida;
    // End of variables declaration//GEN-END:variables
}
