/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;


import BaseDeDatos.Producto;
import javax.swing.JOptionPane;

public class EliminarProducto extends javax.swing.JInternalFrame {
    
    public BaseDeDatos.Producto eliminar;
    
    /**
     * Creates new form EliminarProducto
     */
    public EliminarProducto() {
        initComponents();
        eliminar = new BaseDeDatos.Producto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        txtUnidadMedida = new javax.swing.JTextField();
        txtPrecioUnitario = new javax.swing.JTextField();
        txtRentabilidad = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        txtPorcentajeIva = new javax.swing.JTextField();
        txtPrecioFinal = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtProveedor = new javax.swing.JTextField();
        txtFechaIngreso = new javax.swing.JTextField();
        txtFechaVencimiento = new javax.swing.JTextField();
        consultarBt = new javax.swing.JButton();
        eliminarBt = new javax.swing.JButton();
        txtNombreProducto = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(226, 223, 208));
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(400, 590));

        jLabel1.setText("Codigo Producto");

        jLabel2.setText("Nombre producto");

        jLabel3.setText("Unidad de medida");

        jLabel4.setText("Precio unitario");

        jLabel5.setText("Rentabilidad");

        jLabel6.setText("Precio venta");

        jLabel7.setText("Porcentaje IVA");

        jLabel8.setText("Precio final");

        jLabel9.setText("Cantidad");

        jLabel10.setText("Proveedor ");

        jLabel11.setText("Fecha ingreso");

        jLabel12.setText("Fecha vencimiento");

        txtCodigoProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtUnidadMedida.setEditable(false);

        txtPrecioUnitario.setEditable(false);

        txtRentabilidad.setEditable(false);

        txtPrecioVenta.setEditable(false);

        txtPorcentajeIva.setEditable(false);

        txtPrecioFinal.setEditable(false);

        txtCantidad.setEditable(false);

        txtProveedor.setEditable(false);

        txtFechaIngreso.setEditable(false);

        txtFechaVencimiento.setEditable(false);

        consultarBt.setBackground(new java.awt.Color(233, 115, 0));
        consultarBt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        consultarBt.setForeground(new java.awt.Color(226, 223, 208));
        consultarBt.setText("Consultar");
        consultarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBtActionPerformed(evt);
            }
        });

        eliminarBt.setBackground(new java.awt.Color(233, 115, 0));
        eliminarBt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        eliminarBt.setForeground(new java.awt.Color(226, 223, 208));
        eliminarBt.setText("Eliminar");
        eliminarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtActionPerformed(evt);
            }
        });

        txtNombreProducto.setEditable(false);

        jButton6.setBackground(new java.awt.Color(226, 223, 208));
        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("X");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(consultarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtUnidadMedida)
                            .addComponent(txtPrecioUnitario)
                            .addComponent(txtRentabilidad)
                            .addComponent(txtPrecioVenta)
                            .addComponent(txtPorcentajeIva)
                            .addComponent(txtPrecioFinal)
                            .addComponent(txtCantidad)
                            .addComponent(txtProveedor)
                            .addComponent(txtFechaIngreso)
                            .addComponent(txtFechaVencimiento)
                            .addComponent(txtNombreProducto))))
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton6)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRentabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPorcentajeIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBtActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == consultarBt) {
            int idProducto = Integer.parseInt(txtCodigoProducto.getText());
            

            // Crear una instancia de Consultar
            Producto consultar = new Producto();

            // Obtener los datos del producto
            String[] productoDatos = consultar.obtenerProductoPorId(idProducto);

            if (productoDatos != null) {
                // Llenar los campos de texto con los datos del producto
                txtCodigoProducto.setText(productoDatos[0]); // Código de producto
                txtNombreProducto.setText(productoDatos[1]); // Nombre
                txtUnidadMedida.setText(productoDatos[5]); // unidadMedida
                txtPrecioUnitario.setText(productoDatos[2]); // precioUnitario
                txtRentabilidad.setText(productoDatos[11]); // Rentabilidad
                txtPrecioVenta.setText(productoDatos[12]); // calculaPrecioVenta
                txtPorcentajeIva.setText(productoDatos[10]); // porcentajeIva
                txtPrecioFinal.setText(productoDatos[9]); // precioFinal
                txtCantidad.setText(productoDatos[3]); // cantidad
                txtProveedor.setText(productoDatos[6]); // proveedor
                txtFechaIngreso.setText(productoDatos[7]); // fechaingreso
                txtFechaVencimiento.setText(productoDatos[8]); // fechavencimiento
            } else {
                // Mostrar un mensaje si no se encuentra el usuario
                JOptionPane.showMessageDialog(this, "Producto no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
                // Limpiar los campos si no se encuentra el usuario
                txtCodigoProducto.setText(""); // Código de producto
                txtNombreProducto.setText(""); // Nombre
                txtUnidadMedida.setText(""); // unidadMedida
                txtPrecioUnitario.setText(""); // precioUnitario
                txtRentabilidad.setText(""); // Rentabilidad
                txtPrecioVenta.setText(""); // calculaPrecioVenta
                txtPorcentajeIva.setText(""); // porcentajeIva
                txtPrecioFinal.setText(""); // precioFinal
                txtCantidad.setText(""); // cantidad
                txtProveedor.setText(""); // proveedor
                txtFechaIngreso.setText(""); // fechaingreso
                txtFechaVencimiento.setText(""); // fechavencimiento
            }
        }

    }//GEN-LAST:event_consultarBtActionPerformed

    private void eliminarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtActionPerformed
        if (evt.getSource() == eliminarBt) {
        // Obtener el código de usuario del campo de texto
        int codigoProducto = Integer.parseInt(txtCodigoProducto.getText()); // Esto lanzará una excepción si el texto no es un número
        
        // Llamar al método para eliminar el usuario
        boolean eliminado = eliminar.EliminarProducto(codigoProducto);
        
        if (eliminado) {
            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this, "Producto eliminado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            // Limpiar los campos de texto

            txtCodigoProducto.setText("");
            txtNombreProducto.setText("");
            txtUnidadMedida.setText("");
            txtPrecioUnitario.setText("");
            txtRentabilidad.setText("");
            txtPrecioVenta.setText("");
            txtPorcentajeIva.setText("");
            txtPrecioFinal.setText("");
            txtCantidad.setText("");
            txtProveedor.setText("");
            txtFechaIngreso.setText("");
            txtFechaVencimiento.setText("");
        } else {
            // Mostrar mensaje de error si no se pudo eliminar
            JOptionPane.showMessageDialog(this, "No se encontró el producto o no se pudo eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_eliminarBtActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarBt;
    private javax.swing.JButton eliminarBt;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtFechaIngreso;
    private javax.swing.JTextField txtFechaVencimiento;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPorcentajeIva;
    private javax.swing.JTextField txtPrecioFinal;
    private javax.swing.JTextField txtPrecioUnitario;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtRentabilidad;
    private javax.swing.JTextField txtUnidadMedida;
    // End of variables declaration//GEN-END:variables
}
