/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import BaseDeDatos.UsuariosLogin;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class Login extends javax.swing.JFrame {

    private UsuariosLogin consulta;
    
    
    
    public Login() {
        initComponents();
        ImageIcon icon = new ImageIcon("C:\\Users\\papas\\OneDrive\\Documentos\\NetBeansProjects\\PruebasProyecto\\src\\img\\Logo.png"); // Cambia la ruta a la ubicación de tu imagen
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Usuariotxt = new javax.swing.JTextField();
        contratxt = new javax.swing.JPasswordField();
        Ingresarbt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(226, 223, 208));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {

        });

        Usuariotxt.setBackground(new java.awt.Color(227, 223, 208));
        Usuariotxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Usuariotxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        contratxt.setBackground(new java.awt.Color(226, 223, 208));
        contratxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        contratxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        contratxt.addKeyListener(new java.awt.event.KeyAdapter() {

        });

        Ingresarbt.setBackground(new java.awt.Color(233, 115, 0));
        Ingresarbt.setForeground(new java.awt.Color(226, 223, 208));
        Ingresarbt.setText("INGRESAR");
        Ingresarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarbtActionPerformed(evt);
            }
        });
        Ingresarbt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IngresarbtKeyPressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Usuario.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel1)
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contratxt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(Usuariotxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(Ingresarbt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Usuariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(contratxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Ingresarbt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarbtActionPerformed
        String usuario = Usuariotxt.getText();
        String contrasena = contratxt.getText();
        int codigoUsuario = Integer.parseInt(Usuariotxt.getText());
        if(evt.getSource() == Ingresarbt){
            consulta = new UsuariosLogin();
            if(consulta.validarUsuario(usuario, contrasena)){
                if(codigoUsuario > 1000 && codigoUsuario < 2000){
                Admin ventanaAdmin = new Admin();
                ventanaAdmin.setVisible(true);
                ventanaAdmin.setLocationRelativeTo(null);
                ventanaAdmin.setResizable(false);
                this.setVisible(false);
            }else{
                PosVendedor ventanaVendedor = new PosVendedor();
                ventanaVendedor.setVisible(true);
                ventanaVendedor.setLocationRelativeTo(null);
                ventanaVendedor.setResizable(false);
                this.setVisible(false);
                }
        }else{
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.");
            }
        }
    }//GEN-LAST:event_IngresarbtActionPerformed

    private void IngresarbtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresarbtKeyPressed
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ENTER) {
            String usuario = Usuariotxt.getText();
            String contrasena = contratxt.getText();
            int codigoUsuario = Integer.parseInt(Usuariotxt.getText());
            if(evt.getSource() == Ingresarbt){
                consulta = new UsuariosLogin();
                if(consulta.validarUsuario(usuario, contrasena)){
                    if(codigoUsuario > 1000 && codigoUsuario < 2000){
                        Admin ventanaAdmin = new Admin();
                        ventanaAdmin.setVisible(true);
                        ventanaAdmin.setLocationRelativeTo(null);
                        ventanaAdmin.setResizable(false);
                    this.setVisible(false);
                    }else{
                        ;

                        }
            }else{
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.");
                }
            }  
        }
    }//GEN-LAST:event_IngresarbtKeyPressed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresarbt;
    private javax.swing.JTextField Usuariotxt;
    private javax.swing.JPasswordField contratxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
