/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import BaseDeDatos.Producto;
import javax.swing.JOptionPane;


public class ModificarProducto extends javax.swing.JInternalFrame {
    private BaseDeDatos.Producto modificarproducto;
    private BaseDeDatos.Producto consultarproducto;
    
    public ModificarProducto() {
        initComponents();
        modificarproducto = new BaseDeDatos.Producto();
        consultarproducto = new BaseDeDatos.Producto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigoProducto = new javax.swing.JTextField();
        txtPrecioUnitario = new javax.swing.JTextField();
        txtProveedor = new javax.swing.JTextField();
        txtFechaIngreso = new javax.swing.JTextField();
        txtFechaVencimiento = new javax.swing.JTextField();
        txtUnidadMedida = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        txtRentabilidad = new javax.swing.JTextField();
        consultarBt = new javax.swing.JButton();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPorcentajeIva = new javax.swing.JTextField();
        txtPrecioFinal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        modificar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(226, 223, 208));
        setClosable(true);

        txtCodigoProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtPrecioUnitario.setEditable(false);

        txtProveedor.setEditable(false);

        txtFechaIngreso.setEditable(false);

        txtFechaVencimiento.setEditable(false);

        txtUnidadMedida.setEditable(false);
        txtUnidadMedida.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtNombreProducto.setEditable(false);
        txtNombreProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtRentabilidad.setEditable(false);

        consultarBt.setBackground(new java.awt.Color(233, 115, 0));
        consultarBt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        consultarBt.setForeground(new java.awt.Color(226, 223, 208));
        consultarBt.setText("Consultar");
        consultarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBtActionPerformed(evt);
            }
        });

        txtPrecioVenta.setEditable(false);

        jLabel10.setText("Porcentaje IVA");

        txtPorcentajeIva.setEditable(false);

        txtPrecioFinal.setEditable(false);

        jLabel12.setText("Proveedor");

        jLabel1.setText("Codigo producto");

        txtCantidad.setEditable(false);

        jLabel2.setText("Nombre producto");

        jButton2.setText("Calcular Precio Venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Unidad de medida");

        jButton3.setText("Calcular Precio Final");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio unitario");

        jLabel5.setText("Rentabilidad");

        jLabel7.setText("Cantidad");

        jLabel8.setText("Fecha ingreso");

        jLabel9.setText("Fecha vencimiento");

        modificar.setBackground(new java.awt.Color(233, 115, 0));
        modificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        modificar.setForeground(new java.awt.Color(226, 223, 208));
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(226, 223, 208));
        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("X");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(consultarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtNombreProducto)
                            .addComponent(txtUnidadMedida)
                            .addComponent(txtPrecioUnitario)
                            .addComponent(txtProveedor)
                            .addComponent(txtFechaIngreso)
                            .addComponent(txtFechaVencimiento)
                            .addComponent(txtRentabilidad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrecioVenta)
                            .addComponent(txtPorcentajeIva)
                            .addComponent(txtPrecioFinal)
                            .addComponent(txtCantidad))))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton6)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRentabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPorcentajeIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        if (evt.getSource() == modificar) {
        double codigoproducto = Double.parseDouble(txtCodigoProducto.getText());
        String nombreProducto = txtNombreProducto.getText();
        String unidadMedida = txtUnidadMedida.getText();
        double precioUnitario = Double.parseDouble(txtPrecioUnitario.getText());
        double rentabilidad = Double.parseDouble(txtRentabilidad.getText());
        double precioVenta = Double.parseDouble(txtPrecioVenta.getText());
        double porcentajeIva = Double.parseDouble(txtPorcentajeIva.getText());
        double precioFinal = Double.parseDouble(txtPrecioFinal.getText());
        int cantidad = Integer.parseInt(txtCantidad.getText());
        String proveedor = txtProveedor.getText();
        String fechaIngreso = txtFechaIngreso.getText();
        String fechaVencimiento = txtFechaVencimiento.getText();
            
            // Llamar al método para modificar el producto
            boolean modificado = modificarproducto.ModificarProducto(codigoproducto, nombreProducto, precioUnitario, cantidad, porcentajeIva, unidadMedida, proveedor, fechaIngreso, fechaVencimiento, precioVenta, rentabilidad, precioFinal);

            if (modificado) {
                txtCodigoProducto.setEditable(true);
                txtNombreProducto.setEditable(false);
                txtUnidadMedida.setEditable(false);
                txtPrecioUnitario.setEditable(false);
                txtRentabilidad.setEditable(false);
                txtPrecioVenta.setEditable(false);
                txtPorcentajeIva.setEditable(false);
                txtPrecioFinal.setEditable(false);
                txtCantidad.setEditable(false);
                txtProveedor.setEditable(false);
                txtFechaIngreso.setEditable(false);
                txtFechaVencimiento.setEditable(false);
                
                
                JOptionPane.showMessageDialog(this, "Producto modificado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                // Limpiar los campos de texto
                txtCodigoProducto.setText("");
                txtNombreProducto.setText("");
                txtUnidadMedida.setText("");
                txtPrecioUnitario.setText("");
                txtRentabilidad.setText("");
                txtPrecioVenta.setText("");
                txtPorcentajeIva.setText("");
                txtPrecioFinal.setText("");
                txtCantidad.setText("");
                txtProveedor.setText("");
                txtFechaIngreso.setText("");
                txtFechaVencimiento.setText("");
            } else {
                // Mostrar mensaje de error si no se pudo eliminar
                JOptionPane.showMessageDialog(this, "No se encontró el producto o no se pudo modificar.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_modificarActionPerformed

    
    /*double codigoProducto = Double.parseDouble(txtCodigoProducto.getText());
    
        String nombreProducto = txtNombreProducto.getText();
        String unidadMedida = txtUnidadMedida.getText();
        double precioUnitario = Double.parseDouble(txtPrecioUnitario.getText());
        double rentabilidad = Double.parseDouble(txtRentabilidad.getText());
        double precioVenta = Double.parseDouble(txtPrecioVenta.getText());
        double porcentajeIva = Double.parseDouble(txtPorcentajeIva.getText());
        double precioFinal = Double.parseDouble(txtPrecioFinal.getText());
        int cantidad = Integer.parseInt(txtCantidad.getText());
        String proveedor = txtProveedor.getText();
        String fechaIngreso = txtFechaIngreso.getText();
        String fechaVencimiento = txtFechaVencimiento.getText();*/
    
    
    
    private void consultarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBtActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == consultarBt) {
            int idProducto = Integer.parseInt(txtCodigoProducto.getText());
            txtCodigoProducto.setEditable(false);
            txtNombreProducto.setEditable(true);
            txtUnidadMedida.setEditable(true);
            txtPrecioUnitario.setEditable(true);
            txtRentabilidad.setEditable(true);
            txtPrecioVenta.setEditable(false);
            txtPorcentajeIva.setEditable(true);
            txtPrecioFinal.setEditable(false);
            txtCantidad.setEditable(true);
            txtProveedor.setEditable(true);
            txtFechaIngreso.setEditable(true);
            txtFechaVencimiento.setEditable(true);
            

            // Crear una instancia de Consultar
            consultarproducto = new Producto();

            // Obtener los datos del producto
            String[] productoDatos = consultarproducto.obtenerProductoPorId(idProducto);

            if (productoDatos != null) {
                // Llenar los campos de texto con los datos del producto
                txtCodigoProducto.setText(productoDatos[0]); // Código de producto
                txtNombreProducto.setText(productoDatos[1]); // Nombre
                txtPrecioUnitario.setText(productoDatos[2]); // precioUnitario
                txtCantidad.setText(productoDatos[3]); // cantidad
                txtUnidadMedida.setText(productoDatos[5]); // unidadMedida
                txtProveedor.setText(productoDatos[6]); // proveedor
                txtFechaIngreso.setText(productoDatos[7]); // fechaingreso
                txtFechaVencimiento.setText(productoDatos[8]); // fechavencimiento
                txtPrecioFinal.setText(productoDatos[9]); // precioFinal
                txtPorcentajeIva.setText(productoDatos[10]); // porcentajeIva
                txtRentabilidad.setText(productoDatos[11]); // Rentabilidad
                txtPrecioVenta.setText(productoDatos[12]); // calculaPrecioVenta
            } else {
                // Mostrar un mensaje si no se encuentra el usuario
                JOptionPane.showMessageDialog(this, "producto no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
                // Limpiar los campos si no se encuentra el usuario
                txtCodigoProducto.setText(""); // Código de producto
                txtNombreProducto.setText(""); // Nombre
                txtUnidadMedida.setText(""); // unidadMedida
               txtPrecioUnitario.setText(""); // precioUnitario
                txtRentabilidad.setText(""); // Rentabilidad
                txtPrecioVenta.setText(""); // calculaPrecioVenta
                txtPorcentajeIva.setText(""); // porcentajeIva
                txtPrecioFinal.setText(""); // precioFinal
                txtCantidad.setText(""); // cantidad
                txtProveedor.setText(""); // proveedor
                txtFechaIngreso.setText(""); // fechaingreso
                txtFechaVencimiento.setText(""); // fechavencimiento
            }
        }
    }//GEN-LAST:event_consultarBtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double precioUnitario = Double.parseDouble(txtPrecioUnitario.getText());
        double rentabilidad = Double.parseDouble(txtRentabilidad.getText());
        double resultado = (precioUnitario * rentabilidad)+precioUnitario;
        txtPrecioVenta.setText(String.valueOf(resultado));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if(!"".equals(txtPrecioVenta.getText())){
            double precioVenta = Double.parseDouble(txtPrecioVenta.getText());
            double iva = Double.parseDouble(txtPorcentajeIva.getText());
            double resultado = (precioVenta * iva)+precioVenta;
            txtPrecioFinal.setText(String.valueOf(resultado));
        }else{
            JOptionPane.showMessageDialog(this, "Primero debe calcular el precio de venta");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarBt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtFechaIngreso;
    private javax.swing.JTextField txtFechaVencimiento;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPorcentajeIva;
    private javax.swing.JTextField txtPrecioFinal;
    private javax.swing.JTextField txtPrecioUnitario;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtRentabilidad;
    private javax.swing.JTextField txtUnidadMedida;
    // End of variables declaration//GEN-END:variables
}
