/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import java.util.List;

import javax.swing.table.DefaultTableModel;

import BaseDeDatos.Producto;

/**
 *
 * @author afrp0
 */
public class MostrarInventario extends javax.swing.JInternalFrame {
    DefaultTableModel dmt =  new DefaultTableModel();
    /**
     * Creates new form MostrarInventario
     */
    public MostrarInventario() {
        initComponents();
        String[] titulo = new String[]{"ID", "Nombre", "Unidad medida", "Cantidad", "Precio unitario", "Rentabilidad", "Precio venta", "Porcentaje Iva", "Iva", "Precio final", "Proveedor", "Fecha ingreso", "Fecha vencimiento"};
        dmt.setColumnIdentifiers(titulo);
        
        inventarioTable.setModel(dmt);
        agregar();
        
    }
    
    public void agregar(){
        // Crear una instancia de la clase Producto
        Producto productoDB = new Producto(0, "", "", 0, 0, 0, 0, 0, 0, 0, "", "", ""); // Usamos un constructor vacío
        /*Producto productoPrueba = new Producto(10, " das", "asd ", 10, 1, 10, 10, 10, 10, 10, " asd", "ad ", "ad ");*/
        // Obtener la lista de productos
        List<Producto> productos = productoDB.obtenerTodosLosProductos();
        /*productos.add(productoPrueba);*/
        for (Producto producto : productos) {
            dmt.addRow(new Object[]{
                producto.idproducto,
                producto.nombre,
                producto.unidadMedida,
                producto.cantidadProducto,
                producto.precioUnitario,
                producto.rentabilidad,
                producto.precioVenta,
                producto.porcentajeIva,
                producto.iva,
                producto.precioFinal,
                producto.nombreProveedor,
                producto.fechaIngreso,
                producto.fechaVencimiento
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inventarioTable = new javax.swing.JTable();

        setClosable(true);

        inventarioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Unidad medida", "Cantidad", "Precio unitario", "Rentabilidad", "Precio venta", "Porcentaje IVA", "Iva", "Precio final", "Proveedor", "Fecha ingreso", "Fecha vencimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(inventarioTable);
        inventarioTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable inventarioTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
