/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;
import BaseDeDatos.Pos;
import GUI.CrearCliente;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class POS extends javax.swing.JInternalFrame {

    DefaultTableModel dmt =  new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Ninguna celda será editable
        }
    };
    
    private BaseDeDatos.Cliente consultarCliente;
    private BaseDeDatos.Usuario consultarUsuario;
    private BaseDeDatos.Producto consultarProducto;
    

    public double subtotal = 0;
    public double precioVenta = 0;
    public double iva = 0;
    public double total = 0;
    public double descuento = 0;
    public double totalDescuento = 0;
    public List<Pos> productos = new ArrayList<>();
    
    
    public POS() {
        initComponents();
        consultarCliente = new BaseDeDatos.Cliente();
        consultarUsuario = new BaseDeDatos.Usuario();
        consultarProducto = new BaseDeDatos.Producto();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        codigoProductotxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ivaLB = new javax.swing.JLabel();
        totalLB = new javax.swing.JLabel();
        descuentoLB = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        totalDescuentoLB = new javax.swing.JLabel();
        cantidadProductoJS = new com.toedter.components.JSpinField();
        agregarProductoBt = new javax.swing.JButton();
        facturarBt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cancelarVentaBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        fechaJL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        subtotalLB = new javax.swing.JLabel();
        consultarClienteBt = new javax.swing.JButton();
        documentoClientetxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nombreClienteJL = new javax.swing.JLabel();
        iniciarventa = new javax.swing.JButton();
        nombreVendedorJL = new javax.swing.JLabel();
        idVendedortxt = new javax.swing.JTextField();
        descuentotxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(226, 223, 208));

        jDesktopPane1.setBackground(new java.awt.Color(226, 223, 208));
        jDesktopPane1.setForeground(new java.awt.Color(226, 223, 208));

        codigoProductotxt.setEditable(false);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Fecha");

        ivaLB.setForeground(new java.awt.Color(0, 0, 0));

        totalLB.setForeground(new java.awt.Color(0, 0, 0));

        descuentoLB.setForeground(new java.awt.Color(0, 0, 0));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Total Descuento");

        totalDescuentoLB.setForeground(new java.awt.Color(0, 0, 0));

        cantidadProductoJS.setEnabled(false);
        cantidadProductoJS.setMaximum(100);
        cantidadProductoJS.setMinimum(1);
        cantidadProductoJS.setValue(1);

        agregarProductoBt.setBackground(new java.awt.Color(233, 115, 0));
        agregarProductoBt.setForeground(new java.awt.Color(226, 223, 208));
        agregarProductoBt.setText("Agregar");
        agregarProductoBt.setEnabled(false);
        agregarProductoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoBtActionPerformed(evt);
            }
        });

        facturarBt.setBackground(new java.awt.Color(233, 115, 0));
        facturarBt.setForeground(new java.awt.Color(226, 223, 208));
        facturarBt.setText("Facturar");
        facturarBt.setEnabled(false);
        facturarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturarBtActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingresa codigo producto");

        cancelarVentaBt.setBackground(new java.awt.Color(233, 115, 0));
        cancelarVentaBt.setForeground(new java.awt.Color(226, 223, 208));
        cancelarVentaBt.setText("Cancelar Venta");
        cancelarVentaBt.setEnabled(false);
        cancelarVentaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarVentaBtActionPerformed(evt);
            }
        });

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Unidad medida", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaProductos);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Subtotal");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("IVA");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Total");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Descuento");

        subtotalLB.setForeground(new java.awt.Color(0, 0, 0));

        consultarClienteBt.setText("Consultar Cliente");
        consultarClienteBt.setEnabled(false);
        consultarClienteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarClienteBtActionPerformed(evt);
            }
        });

        documentoClientetxt.setEditable(false);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("N° Documento Cliente");

        nombreClienteJL.setForeground(new java.awt.Color(0, 0, 0));
        nombreClienteJL.setText("Nombre cliente");

        iniciarventa.setBackground(new java.awt.Color(226, 223, 208));
        iniciarventa.setForeground(new java.awt.Color(0, 0, 0));
        iniciarventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N
        iniciarventa.setText("Iniciar venta");
        iniciarventa.setHideActionText(true);
        iniciarventa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iniciarventa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        iniciarventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarventaActionPerformed(evt);
            }
        });

        nombreVendedorJL.setForeground(new java.awt.Color(0, 0, 0));
        nombreVendedorJL.setText("Nombre vendedor");

        descuentotxt.setText("0");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Cantidad");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Descuento");

        jDesktopPane1.setLayer(codigoProductotxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ivaLB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(totalLB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(descuentoLB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(totalDescuentoLB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cantidadProductoJS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(agregarProductoBt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(facturarBt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cancelarVentaBt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(fechaJL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(subtotalLB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(consultarClienteBt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(documentoClientetxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(nombreClienteJL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(iniciarventa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(nombreVendedorJL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(idVendedortxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(descuentotxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultarClienteBt)
                    .addComponent(jLabel1)
                    .addComponent(fechaJL, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarVentaBt)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(codigoProductotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nombreClienteJL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombreVendedorJL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(agregarProductoBt)
                        .addGap(18, 18, 18)
                        .addComponent(facturarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(idVendedortxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(documentoClientetxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(iniciarventa)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(descuentotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(cantidadProductoJS, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11))
                        .addGap(77, 77, 77)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subtotalLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ivaLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(descuentoLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalDescuentoLB, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(iniciarventa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(nombreClienteJL, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(documentoClientetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(consultarClienteBt)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fechaJL, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoProductotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(idVendedortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreVendedorJL)
                                .addGap(288, 288, 288)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantidadProductoJS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(12, 12, 12)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descuentotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(subtotalLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ivaLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(descuentoLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalDescuentoLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(agregarProductoBt)
                        .addComponent(facturarBt))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(cancelarVentaBt)))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarClienteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarClienteBtActionPerformed
        int idCliente = Integer.parseInt(documentoClientetxt.getText());
        if(evt.getSource() == consultarClienteBt){
            // Obtener los datos del usuario
            String[] clienteDatos = consultarCliente.obtenerCliente(idCliente);

            if (clienteDatos != null) {
                // Llenar los campos de texto con los datos del cliente
                documentoClientetxt.setText(clienteDatos[0]); // Código de cliente
                nombreClienteJL.setText(clienteDatos[1]+ " " + clienteDatos[2]); // Nombre y apellido
                
                documentoClientetxt.setEditable(false);
                consultarClienteBt.setEnabled(false);
                
                codigoProductotxt.setEditable(true);
                cantidadProductoJS.setEnabled(true);
                agregarProductoBt.setEnabled(true);
                facturarBt.setEnabled(true);
                cancelarVentaBt.setEnabled(true);
                LocalDateTime hoy = LocalDateTime.now();
                fechaJL.setText((hoy.getYear()+ "-" + hoy.getMonthValue()+ "-"+ hoy.getDayOfMonth()));
                        
            }else{
                // Mostrar un mensaje si no se encuentra el cliente
                JOptionPane.showMessageDialog(this, "Usuario no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
                // Limpiar los campos si no se encuentra el cliente
                documentoClientetxt.setText("");
                
                CrearCliente ventanaCliente = new CrearCliente();
                jDesktopPane1.add(ventanaCliente);
                ventanaCliente.setVisible(true);
                ventanaCliente.setResizable(false);
                
            }
        }
            
    }//GEN-LAST:event_consultarClienteBtActionPerformed

    private void iniciarventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarventaActionPerformed
        int idUsuario = Integer.parseInt(idVendedortxt.getText());
        if(evt.getSource() == iniciarventa){
            // Obtener los datos del usuario
            String[] usuarioDatos = consultarUsuario.obtenerUsuario(idUsuario);

            if (usuarioDatos != null) {
                // Llenar los campos de texto con los datos del usuario
                idVendedortxt.setText(usuarioDatos[3]); // Código de usuario
                nombreVendedorJL.setText(usuarioDatos[1]+ " " + usuarioDatos[2]); // Nombre
                documentoClientetxt.setEditable(true);
                consultarClienteBt.setEnabled(true);
                idVendedortxt.setEditable(false);
                
            }else{
                // Mostrar un mensaje si no se encuentra el usuario
                JOptionPane.showMessageDialog(this, "Usuario no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
                // Limpiar los campos si no se encuentra el usuario
                idVendedortxt.setText("");
                nombreVendedorJL.setText("Nombre vendedor");
            }
        }
    }//GEN-LAST:event_iniciarventaActionPerformed

    private void agregarProductoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoBtActionPerformed
        double codigoProducto = Double.parseDouble(codigoProductotxt.getText());
        int cantidadProductoPedido = cantidadProductoJS.getValue();
        double descuentoProductoPedido = Double.parseDouble(descuentotxt.getText());
        
        String[] titulo = new String[]{"Codigo", "Nombre", "Unidad medida", "Cantidad","Precio final",};
        dmt.setColumnIdentifiers(titulo);
        
        
        if(evt.getSource() == agregarProductoBt){
            if(descuentoProductoPedido <= 50){
            Pos posDB = new Pos(0, "", "", 0, 0, 0, 0, 0, 0);
            if(consultarProducto.ProductoExistente(codigoProducto) == true){
                
                List<Pos> producto = posDB.obtenerProducto(codigoProducto, cantidadProductoPedido, descuentoProductoPedido);
                for (Pos i : producto){
                    Pos producto_1 = new Pos(i.idproducto, i.nombre, i.unidadMedida, i.cantidadProducto, i.precioVenta, i.iva, i.precioFinal, i.cantidadProductoPedido, descuentoProductoPedido);
                    productos.add(producto_1);
                }
                precioVenta = 0;
                iva = 0;
                total = 0;
                descuento = 0;
                totalDescuento = 0;
                
                dmt.getDataVector().removeAllElements();
                for (Pos i : productos){
                    if(i.cantidadProductoPedido < i.cantidadProducto){
                        if (i.descuentoProductoPedido > 0){
                        dmt.addRow(new Object[]{
                            i.idproducto,
                            i.nombre,
                            i.unidadMedida,
                            i.cantidadProductoPedido,
                            i.precioFinal - (i.precioFinal * (i.descuentoProductoPedido * 0.01))
                            }
                            );

                        }else{
                            dmt.addRow(new Object[]{
                                i.idproducto,
                                i.nombre,
                                i.unidadMedida,
                                i.cantidadProductoPedido,
                                i.precioFinal - (i.precioFinal * (i.descuentoProductoPedido * 0.01))
                                }
                                );

                        }tablaProductos.setModel(dmt);

                        precioVenta = precioVenta + (i.precioVenta * i.cantidadProductoPedido);
                        subtotalLB.setText(String.valueOf(String.format("%.2f",precioVenta)));

                        iva = iva + (i.iva * i.cantidadProductoPedido);
                        ivaLB.setText(String.valueOf(String.format("%.2f",iva)));

                        total = precioVenta + iva;
                        totalLB.setText(String.valueOf(String.format("%.2f",total)));

                        descuento = descuento + ((i.precioFinal * (i.descuentoProductoPedido * 0.01)) * i.cantidadProductoPedido);
                        descuentoLB.setText(String.valueOf(String.format("%.2f",descuento)));

                        totalDescuento = total - descuento;
                        totalDescuentoLB.setText(String.valueOf(String.format("%.2f",totalDescuento)));

                        

                }else{
                        JOptionPane.showMessageDialog(this, "La cantidad no esta disponible.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
            }
        }else{
                JOptionPane.showMessageDialog(this, "Codigo de producto no existe.", "Error", JOptionPane.ERROR_MESSAGE);
            
            }
        }else{
                JOptionPane.showMessageDialog(this, "El descuento maximo es 50%.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        codigoProductotxt.setText("");
        cantidadProductoJS.setValue(1);
        descuentotxt.setText("0");
    }//GEN-LAST:event_agregarProductoBtActionPerformed

    private void cancelarVentaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarVentaBtActionPerformed
        if(evt.getSource() == cancelarVentaBt){
            
            dmt.getDataVector().removeAllElements();
            dmt.fireTableDataChanged();
            
            idVendedortxt.setText("");
            nombreVendedorJL.setText("Nombre vendedor");
            idVendedortxt.setEditable(true);
            
            nombreClienteJL.setText("Nombre cliente");
            documentoClientetxt.setText("");
            documentoClientetxt.setEditable(false);
            
            fechaJL.setText("");
            codigoProductotxt.setEditable(false);
            codigoProductotxt.setText("");
            
            cantidadProductoJS.setValue(1);
            cantidadProductoJS.setEnabled(false);
            
            descuentotxt.setEditable(false);
            descuentotxt.setText("0");
            
            agregarProductoBt.setEnabled(false);
            facturarBt.setEnabled(false);
            cancelarVentaBt.setEnabled(false);
            
            productos.clear();
            subtotalLB.setText("");
            ivaLB.setText("");
            totalLB.setText("");
            descuentoLB.setText("");
            totalDescuentoLB.setText("");
            
            
            
            
        
        }
    }//GEN-LAST:event_cancelarVentaBtActionPerformed

    private void facturarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturarBtActionPerformed
        
        
    }//GEN-LAST:event_facturarBtActionPerformed
    /*ConsultarUsuario.setEnabled(true);*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarProductoBt;
    private javax.swing.JButton cancelarVentaBt;
    private com.toedter.components.JSpinField cantidadProductoJS;
    private javax.swing.JTextField codigoProductotxt;
    private javax.swing.JButton consultarClienteBt;
    private javax.swing.JLabel descuentoLB;
    private javax.swing.JTextField descuentotxt;
    private javax.swing.JTextField documentoClientetxt;
    private javax.swing.JButton facturarBt;
    private javax.swing.JLabel fechaJL;
    private javax.swing.JTextField idVendedortxt;
    private javax.swing.JButton iniciarventa;
    private javax.swing.JLabel ivaLB;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreClienteJL;
    private javax.swing.JLabel nombreVendedorJL;
    private javax.swing.JLabel subtotalLB;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JLabel totalDescuentoLB;
    private javax.swing.JLabel totalLB;
    // End of variables declaration//GEN-END:variables
}